//@ts-nocheck
import Head from "next/head";
import { Inter } from "@next/font/google";
import { BsFillMoonStarsFill } from "react-icons/bs";
import { AiFillTwitterCircle, AiFillLinkedin } from "react-icons/ai";
import Image from "next/image";
import deved from "../public/dev-ed-wave.png";
import design from "../public/design.png";
import glasses from "../public/glasses.png";
import code from "../public/code.png";
import tlf from "../public/tlf-screenshot.png";
import closingPacks from "../public/closing-packs.png";
import dojoPrototype from "../public/dojo-prototype.png";
import musicStyleGuide from "../public/music-styleguide.png";
import mobileClosingPacks from "../public/mobile-closingpacks.png";
import mobileTLF from "../public/mobile-tlf.png";

import { useState } from "react";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);

  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Jordon van Leenen Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="bg-gray-80 px-10 dark:bg-gray-900 md:px-20 lg:px-40">
        <section className="min-h-screen">
          <nav className="py-10 mb-12 flex justify-between">
            <h1 className="text-xl font-burtons dark:text-gray-300">
              Portfolio
            </h1>
            <ul className="flex items-center">
              <li>
                <BsFillMoonStarsFill
                  onClick={() => setDarkMode(!darkMode)}
                  className="cursor-pointer text-2xl"
                />
              </li>
              <li>
                <a
                  className=" bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-8"
                  href="/downloads/JordonvanLeenen_Resume 2023.pdf"
                  download="JordonvanLeenen_Resume 2023.pdf"
                >
                  Resume
                </a>
              </li>
            </ul>
          </nav>
          <div className="text-center">
            <h2 className="text-5xl py-2 text-teal-600 font-medium dark:text-teal-400 md:text-6xl">
              Jordon van Leenen
            </h2>
            <h3 className="text-2xl py-2 md:text-3xl dark:text-gray-600">
              Developer and Designer
            </h3>
            <p className="font-semibold text-md mt-5 leading-8 text-gray-800 md:text-xl max-w-xl mx-auto dark:text-gray-300">
              Version Control <br />
            </p>
            <p className="text-sm leading-8 text-gray-600 md:text-xl max-w-xl mx-auto dark:text-gray-300">
              [Github, Bitbucket, Azure Devops]
            </p>
            <p className="font-semibold text-md mt-5 leading-8 text-gray-800 md:text-lg max-w-xl mx-auto dark:text-gray-300">
              Mobile Apps
            </p>
            <p className="text-sm leading-8 text-gray-600 md:text-xl max-w-xl mx-auto dark:text-gray-300">
              [Java, Swift, Javascript, C#, React Native,Typescript]
            </p>
            <p className="font-semibold text-md mt-3 leading-8 text-gray-800 md:text-xl max-w-xl mx-auto dark:text-gray-300">
              Web
            </p>
            <p className="text-sm leading-8 text-gray-600 md:text-xl max-w-xl mx-auto dark:text-gray-300">
              [Shopify, React, Javascript,Liquid, HTML, scss/css]
            </p>
          </div>
          <div className="text-5xl flex justify-center gap-16 mt-10 text-gray-600">
            <a href="https://twitter.com/JordonTech">
              <AiFillTwitterCircle />
            </a>

            <a href="https://www.linkedin.com/in/jordonvanleenen/">
              <AiFillLinkedin />
            </a>
          </div>
          <div className="mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 relative overflow-hidden mt-20 md:h-96 md:w-96">
            <Image src={deved} layout="fill" objectFit="cover" />
          </div>
        </section>

        <section>
          <div className="py-5">
            <h3 className="text-center text-3xl py-1 dark:text-gray-300">
              Services I Offer
            </h3>
            <p className="text-center text-md py-2 leading-8 text-gray-80 dark:text-gray-300">
              Great <span className="text-teal-500">team player</span> and{" "}
              collaborator. <br />
              <span className="text-teal-500">Hungry</span> to impact with
              <span className="text-teal-500"> positive</span> energy and work
              ethic. <br /> Click one of the media icons above to see a{" "}
              <span className="text-teal-500">diverse</span> range of projects
              and work history.
            </p>
          </div>
          <div className="lg:flex gap-10 dark:">
            <div className="bg-gray-95 text-center shadow-md p-10 rounded-xl my-10 flex-1 dark:shadow-white">
              <Image
                className="mx-auto"
                src={glasses}
                width={100}
                height={100}
              />
              <h3 className="text-lg font-medium pt-8 pb-2 dark:text-gray-300">
                Beautiful Designs
              </h3>
              <h4 className="text-teal-600 py-4">Design tools I use</h4>
              <p className="text-gray-800 py-1 dark:text-gray-200">
                Illustrator
              </p>
              <p className="text-gray-800 py-1 dark:text-gray-200">Figma</p>
            </div>
            <div className="bg-gray-95 text-center shadow-md p-10 rounded-xl my-10 flex-1 dark:shadow-white">
              <Image className="mx-auto" src={code} width={100} height={100} />
              <h3 className="text-lg font-medium pt-8 pb-10 dark:text-gray-300">
                Code Projects
              </h3>
              <a className="text-teal-600" href="https://github.com/Javal1n">
                Click for Github
              </a>
            </div>
          </div>
        </section>

        <section className="py-10">
          <div className="flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap">
            <div className="basis-1/3 flex-1">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={tlf}
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={closingPacks}
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={dojoPrototype}
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={musicStyleGuide}
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={mobileClosingPacks}
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={mobileTLF}
              />
            </div>
          </div>
        </section>
      </main>
    </div>
  );
}
